<a href="https://colab.research.google.com/github/folaro/sudokuSolver/blob/main/sudokuSolver.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#待求解宫格
grid2 = [[0,0,0,0,5,0,8,0,0],
     [0,0,7,0,0,1,6,0,0],
     [0,0,0,7,0,2,0,3,0],
     [0,0,8,0,0,0,0,0,0],
     [0,0,0,2,9,0,3,7,0],
     [4,0,0,0,0,0,0,0,5],
     [8,0,2,0,0,7,0,0,0],
     [0,4,0,0,3,0,0,1,8],
     [0,0,6,0,0,0,0,0,0]]
grid = [[0,0,0,3,0,7,4,0,0],
     [9,0,0,0,0,4,0,0,8],
     [3,7,0,0,0,0,0,6,0],
     [8,2,0,9,0,0,6,0,0],
     [0,0,1,2,0,0,9,0,4],
     [0,4,0,0,3,8,0,5,0],
     [2,0,8,6,9,0,7,0,0],
     [0,9,0,0,0,0,0,0,0],
     [7,5,0,0,0,0,0,0,6]]

In [ ]:
import numpy as np
print(np.matrix(grid))

[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 7 9]]


In [ ]:
def possible(y,x,n):
  global grid
  for i in range(0,9):
    if grid[y][i]==n:
      return False
  for i in range(0,9):
    if grid[i][x]==n:
      return False
  xx = (x//3)*3
  yy = (y//3)*3
  for i in range(0,3):
    for j in range(0,3):
      if grid[yy+i][xx+j]==n:
        return False
  return True


In [ ]:
possible(4,4,3)

False

In [ ]:
possible(4,4,5)

False

In [ ]:
def solve():
  global grid
  for y in range(9):
    for x in range(9):
      if grid[y][x]==0:
        for n in range(1,10):
          if possible(y,x,n):
            grid[y][x]=n
            solve()
            grid[y][x]=0
        return
  print(np.matrix(grid))
  input("More?")

In [ ]:
solve()

[[1 8 5 3 6 7 4 2 9]
 [9 6 2 5 1 4 3 7 8]
 [3 7 4 8 2 9 5 6 1]
 [8 2 7 9 4 5 6 1 3]
 [5 3 1 2 7 6 9 8 4]
 [6 4 9 1 3 8 2 5 7]
 [2 1 8 6 9 3 7 4 5]
 [4 9 6 7 5 1 8 3 2]
 [7 5 3 4 8 2 1 9 6]]
More?
